sudo: required
language: go
go:
- 1.8.5
before_install:
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/golang/go/src/cmd/vet
- go get github.com/onsi/gomega
- go get -u github.com/securego/gosec/cmd/gosec/...
install: true
script: sudo env "PATH=$PATH" src/bosh-softlayer-cpi/bin/ci
branches:
  only:
  - master
