---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
- name: stemcell
- name: bosh-cpi-release
- name: bats
- name: deployment
- name: stemcell-version
run:
  path: bosh-cpi-release/ci/tasks/run-bats.sh
params:
  BASE_OS:                      replace-me
  BAT_VCAP_PASSWORD:            replace-me
  BAT_SECOND_STATIC_IP:         replace-me
  BAT_NETWORK_STATIC_IP:        replace-me
  BAT_NETWORK_CIDR:             replace-me
  BAT_NETWORK_RESERVED_RANGE:   replace-me
  BAT_NETWORK_STATIC_RANGE:     replace-me
  BAT_NETWORK_GATEWAY:          replace-me
  SL_DATACENTER:                replace-me
  SL_VLAN_PUBLIC:               replace-me
  SL_VLAN_PRIVATE:              replace-me
  SL_VM_NAME_PREFIX:            replace-me
  SL_VM_DOMAIN:                 softlayer.com


