---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-lite-ci

inputs:
- name: bosh-cpi-release

run:
  path: bosh-cpi-release/ci/tasks/run-lifecycle.sh

params:
  SL_USERNAME:           replace-me
  SL_API_KEY:            replace-me