---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
  - name: bosh-cpi-dev-artifacts # -++ used for deployment manifest referenced by manifest_path
  - name: version-semver         # -//
  - name: bosh-cpi-release
  - name: bosh-init              # --- bosh-init executable to do deploy
  - name: bosh-release           # -\
  - name: stemcell
outputs:
  - name: deployment
run:
  path: bosh-cpi-release/ci/tasks/setup-director.sh
params:
  BASE_OS:                    replace-me
  SL_USERNAME:                replace-me
  SL_API_KEY:                 replace-me
  SL_DATACENTER:              replace-me
  SL_VLAN_PUBLIC:             replace-me
  SL_VLAN_PRIVATE:            replace-me
  SL_VM_NAME_PREFIX:          replace-me
  SL_VM_DOMAIN:               softlayer.com
  BOSH_INIT_LOG_LEVEL:        warn
